#!/bin/sh

FAVOURITE_BROWSERS='konqueror mozilla netscape encompass nautilus amaya lynx'
FAVOURITE_TERM_BROWSERS='lynx links w3c'

ARGS="$@"
if test "x$ARGS" = "x"; then
	ARGS="$JPATH/org/jumpgate.html"
fi

if xisrunning; then
	runoneof "$FAVOURITE_BROWSERS" "$@" &
else
	runoneof "$FAVOURITE_TERM_BROWSERS" "$@"
fi

# netscape "file://$PWD/$@" &
