#!/bin/sh
## browse: given a url (or possibly path), opens up the users favourite browser

FAVOURITE_BROWSERS='konqueror opera encompass firefox firebird phoenix mozilla galeon skipstone netscape amaya links lynx w3m w3c jazilla'
FAVOURITE_TERM_BROWSERS='links lynx w3m w3c'

ARGS="$@"
if test "x$ARGS" = "x"; then
	ARGS="$JPATH/org/jumpgate.html"
fi

if xisrunning; then
	runoneof "$FAVOURITE_BROWSERS" "$@" &
else
	runoneof "$FAVOURITE_TERM_BROWSERS" "$@"
fi

# netscape "file://$PWD/$@" &
