#!/bin/sh
## explore: given a path or url, opens up the user's favourite file manager, or browser if neccessary

## TODO BUG: if target is a local file (esp. html), then konqueror / file reader should be opened; but actually this was getting called (which produced an extra broken empty tab): /usr/kde/3.5/bin/konqueror konqueror /path/to/file.html
jsh_find_favourite() {
	for X
	do which "$X" >/dev/null && echo "$X" && return
	done
	echo "[FAIL] jsh_find_favourites: $*" >&2
	return 9
}

[ -z "$FAVOURITE_EXPLORERS" ] && FAVOURITE_EXPLORERS="konqueror dolphin nautilus kvfm kfmclient explorer.exe xdg-open"

explorer="$(jsh_find_favourite $FAVOURITE_EXPLORERS)"

## TODO: When running konqueror, I used to want: >/dev/null 2>&1 

if [ -z "$*" ]
then "$explorer" . &
else "$explorer" "$@" &
fi
