#!/bin/sh

# if test ! -e "$@"; then
  # echo 0
# else
  awk ' END { print NR } ' "$@"
# fi

# LINES=0;
# cat "$@" |
	# while read L; do
		# LINES=$(($LINES+1));
		# echo "$LINES"
	# done;
# echo "$LINES"
