#!/bin/sh

# jsh-depends: cursebold cursered cursenorm jfcsh

## Default behaviour is to display dropped lines in red, and new lines in white
## The option -oneway means dropped lines will not be reported.

BOTHWAYS=true
if [ "$1" = -oneway ]
then BOTHWAYS=; shift
fi

FILEA="$1"
FILEB="$2"
shift
shift

## jfc bridge (for speed)
# if test `jwhich jfc`
# then JFCCOM="jfc simple oneway"
# else JFCCOM="jfcsh -sorted"
# fi
#JFCCOM="jfcsh -sorted"
JFCCOM="jfcsh"

#reverse_diff() {
#	diff "$2" "$1"
#}
#JFCCOM="reverse_diff"
#BOTHWAYS=

# This is what jfcsh does
#trimmed_diff() {
#	diff "$2" "$1" | grep '^> ' | sed 's+^> ++'
#}
#JFCCOM="trimmed_diff"

## Optionally, check for lines which have been dropped:

if [ -n "$BOTHWAYS" ]
then
	OTHER="`$JFCCOM "$FILEB" "$FILEA"`"
	if [ -n "$OTHER" ]
	then
		# echo
		# echo `cursered``cursebold`"<<< DIED:"
		echo "$OTHER" |
		sed "s+^.*$+`cursered;cursebold`\0`cursenorm`+"
		# echo ">>>"`cursenorm`
		# echo
	fi
fi

## Now check for lines which have been added:

# cursegreen # ;cursebold
$JFCCOM "$FILEA" "$FILEB"
# cursenorm
