#!/bin/sh

# #!/usr/local/bin/zsh

# Problems without zsh - why?  `which $FILE` doesn't work in sh
# OK now changed back to using `which inj $FILE`

if test "$1x$2" = "x"; then
  echo 'runoneof "<executables>" "<args>"'
  echo '  Will find and run on the first working executable!'
fi

LIST=$1;
shift
# ARGS="$@";

# echo "l='$LIST' a='$ARGS'"

for FILE in $LIST; do
  # echo "file: $FILE"
  TRY=`jwhich inj $FILE`
  # TRY=`which $FILE`
  # Uncomment this, disrupt $? next line   echo 'Got: "'$TRY'"'
  if test "$?" = "0"; then
    # echo "runoneof: trying $TRY"
    $TRY "$@"
    if test "$?" = "0"; then
      # echo "$TRY done good"
      # echo "runoneof: worked on $TRY"
      exit 0
    else
      # echo "$TRY done bad"
      echo 'runoneof: "'$TRY'" failed :-('
    fi
  else
    echo "runoneof: Did not find $FILE in path"
  fi
done

echo "runoneof: could not find working exe"
exit 1
