#!/bin/sh

if test "$1x$2" = "x"; then
  echo 'runoneof [-notinj] "<executables>" <args...>'
  echo '  Will find and run on the first working executable!'
fi

INJOPT="inj"
if test "$1" = "-notinj"; then
	shift
	INJOPT=""
fi

LIST=$1;
shift

for FILE in $LIST; do

  # echo "file: $FILE" >&2

  # which may not be present
  TRY=`jwhich $INJOPT "$FILE"`

  # WARNING: don't disrupt $? next line
  if test "$?" = "0"; then

    # echo "runoneof: trying $TRY $*" >&2

    $TRY "$@"

    # WARNING: don't disrupt $? next line
    if test "$?" = "0"; then

      # echo "runoneof: worked on $TRY" >&2
      exit 0

    else

      echo 'runoneof: failed on "'$TRY'" :-(' >&2

    fi

  else
    echo "runoneof: Did not find $FILE in path" >&2
  fi

done

echo "runoneof: could not find working exe" >&2
exit 1
