#!/bin/bash

# /bin/grep -v $@

## BUG: inefficient (runs a new sh+grep for every arg!)

## NOTABUG: "mount | ungrep bind" was not working - ah this was because of colour highlighting, and ungrep expects word

# Now changed to recursive method
# multiple arguments are multiple ungreps, not classic grep arguments.

. importshfn ungrep

if [ "$1" = "" ]
then cat
else
	STR="$1"
	shift
	# /bin/grep -v "$STR" | ungrep "$@"
	/bin/grep -v "\<`toregexp "$STR"`\>" | ungrep "$@"
fi
