## TODO: obtain more commands from zsh-history
COMMANDS=(ls man tar ssh rsync mplayer btdownloadcurses grep diff chmod chown java jar cvs svn ci co)

## Method 1: pre-generate rules for selected commands

# echo "### Generated by gen_compctl_rules"

for COMMAND in $COMMANDS
do

	# echo -n -e "\r$COMMANDS" | sed "s+\<$COMMAND\>+>>\0<<+"
	echo -n "$COMMAND " >&2
	OPTIONS="--help "`memo extractpossoptsfrommanpage "$COMMAND" 2>/dev/null | tr '\n' ' '`
	## -c commands
	## -f files
	## -k options
	## -r running jobs
	## -u users
	# echo "compctl -f -k \"($OPTIONS)\" $COMMAND"
	# EXPLANATION="Multiple matches found, please choose:                       (btw joey is cool)"
	## -X \"$EXPLANATION\"
	# echo "compctl -u -r -c -f -k \"($OPTIONS)\" $COMMAND"
	compctl -u -r -c -f -k "($OPTIONS)" $COMMAND -tn

done

echo >&2

## Method 2: generate when asked for (slows down completion!) (cannot turn it off when other command compctl's have matched, despite -tn's and definition before others)

if [ bill_gates = a_good_bloke ]
then

	function joeyComplete {
		read -c COMMAND ARGS
		OPTIONS=(--help `memo extractpossoptsfrommanpage "$COMMAND" 2>/dev/null | tr '\n' ' '`)
		reply=($OPTIONS)
	}

	compctl -K joeyComplete "*" -tn

fi
