#!/bin/sh

## DISABLED
## We now simply add $HOME/bin to their path in startj.

exit 0

## This means all $JPATH/bin should move to $HOME/bin ok?

## WARNING:
## If you re-enable it, the `jwhich jfc` check used by jwatchcomp will fail

cd "$JPATH/tools/"
# "rm" *
ln -sf ../bin/* .
#FILES=`find "$JPATH/code/shellscript/" -name "*" | tr "\n" " "`
#echo "$FILES"
#ln -sf $FILES .
