#!/bin/sh

### For cable modem:

# ppp-updateip
# exit 0



## For phone modem:
echo -n `nicedate`"/ ensure-ip-state: "

## Determine current state
PPPON=false
if [ -r /var/run/ppp0.pid ]; then
  # Doesn't work on Mandrake
  PID=`cat /var/run/ppp0.pid`;
  JOB=`ps -A | grep '^[ 	]*$PID\>'`
  if [ "$JOB" = "" -o "$PID" = "" ]
	then
    printf "(has pid but not running) " >&2
    # printf "(checking for other pppd) " >&2
    # rm -f /var/run/ppp0.pid
		if ps -A | grep "\<pppd\>" >/dev/null
		then
			printf "(found pppd with other pid) "
			PPPON=true
		fi
  else
    echo -n "(on) "
    PPPON=true
  fi
else
  # So for Mandrake:
  FIND=`ps -A | grep '\<pppd$'`
  if [ "$FIND" = "" ]
	then
    echo -n "(off) "
  else
    echo -n "(on but no PID) "
    PPPON=true
  fi
fi

## What is the desired state (our orders)?
if [ ! -f /var/hwi/orders/ensure-ip-up ]; then
  if [ "$PPPON" = "true" ]
	then
    echo "Going down"
    killall pppd
    exit 0
    # kill -INT `cat /var/run/ppp0.pid` || echo "Kill failed"
  else
    echo "Down OK"
    exit 0
  fi
fi

if [ "$PPPON" = "true" ]
then
  echo "Up OK"
  exit 0
fi

echo "Coming up"
## If you run in debug mode and save data to file: (really should continually purge it with printf "" > )
'rm' -f $JPATH/logs/packetdata.ppp
## One of kdebug 0 | nolog prevents endless send rcvd logging
/usr/sbin/pppd kdebug 0 nolog call provider
# /usr/sbin/pppd record $JPATH/logs/packetdata.ppp call provider

# echo "Up ok.  Waiting before performing IP update."
# sleep 60

cp /stuff/portablelinux/etc/resolv.conf /etc/resolv.conf

# /etc/init.d/iptables restart

echo "Updating IP"
ppp-updateip

exit 0
